TG_MODEL: mistralai/Mixtral-8x22B-Instruct-v0.1
EMBED_MODEL: mixedbread-ai/mxbai-embed-large-v1
ANTHROPIC_MODEL: claude-3-5-sonnet-20240620
ANTHROPIC_PROMPT_CACHING: prompt-caching-2024-07-31
OUTPUT_DIR: outputs
PAGE_DELIMITER: <||WXb23TXrUn3Rxz00yNNr89HV||>